### PR TITLE
add linux and macos Installation guide link

### PR DESCRIPTION
**Pull request by avsingh999**
#720 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by avsingh999** [comment]
@vivonk  please review me

**Comment by vivonk** [comment]
can you revert it to the develop branch first?

**Comment by VibhorCodecianGupta** [comment]
@vivonk #673 does this change and more.

**Comment by avsingh999** [comment]
@vivonk #725 I have opened another pr for this. Please review.
thank you  : )

**Comment by kmehant** [comment]
Please look at it! https://github.com/scorelab/Bassa/pull/725#issuecomment-498637043

**Pull request closed without merging**
