### PR TITLE
`docker-compose.yml` to run Bassa

### LINKED ISSUE #248: docker-compose.yml to run Bassa

### PR DESCRIPTION
**Pull request by agentmilindu**
Fix #248

### CODE REVIEW

**Comment by agentmilindu** [comment]
@malithsen @rehrumesh @kmehant Please review.

**Comment by kmehant** [comment]
@agentmilindu Looks like the branch ```feature/248-docker-compose``` is not in sync with develop,because i see a lot of other contributed commits, which got merged recently

**Comment by agentmilindu** [comment]
@kmehant True, the reason is `develop` is behind the `master` branch. People create PRs to `master` instead to `develop`, that's why. Have to fix it.

**Comment by kmehant** [comment]
@agentmilindu oh now i observed that, it's ```develop```. I thought it as master :D

**Pull request merged**
