### PR TITLE
Locust load testing file

### PR DESCRIPTION
**Pull request by selfisekai**
## Description

providing a Locustfile for load testing with Locust framework

## Related Issue

Google Code-In 2019 task

## Motivation and Context

make testing performance of specific API endpoints easier

## How Has This Been Tested?

ran those Locust tests [Bassa wiki guide link placeholder]

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by selfisekai** [comment]
because I can't add the changes to Bassa Wiki, here they are: https://privatebin.net/?504f8b555523c210#Eiz7ZWNkdxLPo52aNrHRftLSYdhvTTMpDsqkNrKbKK7w

**Comment by kmehant** [comment]
Can you move this file to Bassa API tests folder :)

**Comment by selfisekai** [comment]
@kmehant done

**Comment by selfisekai** [comment]
oh

**Comment by selfisekai** [comment]
I created this tool to automate these tests. enjoy.
https://github.com/selfisekai/auto-locust

**Comment by sanjulamadurapperuma** [comment]
@kmehant @JaDogg can this PR be merged if the issues shown by the Codacy PR review can be ignored?

**Pull request merged**
