### PR TITLE
updated readme , added Gifs

### PR DESCRIPTION
**Pull request by iammosespaulr**

### CODE REVIEW

**Comment by rehrumesh** [comment]
Can you make the font large in terminal? Hard to see the commands. Maybe I am too old.

**Comment by iammosespaulr** [comment]
lol .. ok .

**Comment by iammosespaulr** [comment]
@rehrumesh Changes have been made

**Comment by rehrumesh** [comment]
LGTM.
@malithsen @agentmilindu

**Comment by iammosespaulr** [comment]
@malithsen @agentmilindu please review and merge

**Comment by malithsen** [comment]
merged with #412 
Please work on a new branch when issuing a PR in future :)

**Pull request closed without merging**
