### PR TITLE
Created components: Admin and Login with respective tests

### PR DESCRIPTION
**Pull request by singhrohan62**
With the submission of this pull request, we have completed creation of all components which will be used inside our Bassa application. This pull request contains components `Admin` and `Login` along with their respective tests. Moreover, feature suggested by @kmehant is also added to the `Completed_Component`.

## Description
In the previous [pull request](https://github.com/scorelab/Bassa/pull/788), components `Dashboard`, and components for queued and completed downloads, `Queued_Component` and `Completed_Component` were completed. In this pull request, remaining components are now added to the Bassa React application along with the feature of sharing the completed, compressed downloaded files.

## Related Issue
[Issue 1](https://github.com/scorelab/Bassa/issues/795)
[Issue 2](https://github.com/scorelab/Bassa/issues/805)

## How Has This Been Tested?
The components have been tested using Jest test runner and Enzyme test utility.

## Screenshots (In case of UI changes):
Screenshot from 2019-06-22 23-12-14
Login Component

Screenshot from 2019-06-22 23-13-11
Admin Component

Screenshot from 2019-06-22 23-35-56
No completed file selected in `Completed` Component

Screenshot from 2019-06-22 23-36-02
Any 2 files selected in `Completed` Component

Screenshot from 2019-06-22 23-39-37
User can also share link of the files from `Dashboard` component also :smiley: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by vivonk** [comment]
@singhrohan62 shouldn't we make the `Download`, `Start` other buttons in a vertical linear pattern. Right now, each item is covering same space but not all elements have same alignments. It will look better in UI if we have a similar vertical alignment.

**Comment by singhrohan62** [comment]
Hi @vivonk , made changes according to your suggestions. Now, download, delete and approve button present in the components: Completed, Queued and Admin will be aligned in right direction.

**Comment by vivonk** [comment]
@singhrohan62 can you please send the Screenshots as well?

**Comment by singhrohan62** [comment]
Screenshot from 2019-06-23 10-53-06
Screenshot from 2019-06-23 10-53-41
Screenshot from 2019-06-23 10-56-53
Here are the screenshots @vivonk

**Pull request merged**
