### PR TITLE
Attaching github link with Bassa-logo button on nav-bar.

### PR DESCRIPTION
**Pull request by demon-36**
Bassa-logo button on nav-bar will clicked then it will redirect to github link of Bassa in new tab.

## Description

After logging in when Bassa-logo button on top-left of nav-bar will clicked then it will redirect user to Bassa's Github profile.

## Motivation and Context

It will help user to connect with Bassa's developers and its code-base directly.

## How Has This Been Tested?

I have tested the same on my local machine.

## Screenshots (In case of UI changes):
ezgif com-video-to-gif

## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [] All new and existing tests passed.

### CODE REVIEW

**Comment by demon-36** [comment]
@vivonk please have a look

**Comment by avsingh999** [comment]
Hi @demon-36 can you add screenshot or Gif.
thanks : )

**Comment by demon-36** [comment]
@avsingh999 I have added a gif for above improvement. :)

**Comment by demon-36** [comment]
whoaa first PR got merged. Thanks @vivonk ;)

**Pull request merged**
