### PR TITLE
How to use Bassa video

### PR DESCRIPTION
**Pull request by padamchopra**
Update readme.md with the link for watching the video tutorial on "How to use SCoRe's Bassa"
[GCI 2017]

### CODE REVIEW

**Comment by padamchopra** [comment]
@saisankargochhayat Here's the PR for the same :)

**Comment by JaDogg** [comment]
Looks good to me.

**Comment by saisankargochhayat** [comment]
You are supposed to make the pr to the Bassa repo instead of score:master

**Comment by padamchopra** [comment]
I think I've made the PR correctly, some of my PRs were even merged and they were of the same way. `Score:master` corresponds to the `master` branch of `Bassa` repo of `scorelab` account and `padamchopra:howtousevideo` corresponds to `howtousevideo` branch of `Bassa` repo but of `padamchopra`'s account :worried:

**Comment by agentmilindu** [comment]
@malithsen @rehrumesh I am merging this PR

**Pull request merged**
