### PR TITLE
[Unit test] Switch from PhantomJS to Chrome - Admin service unit tests

### PR DESCRIPTION
**Pull request by rajikaimal**
- Change configurations to Chrome.
- Implement AdminService unit tests.
[505dda2](https://github.com/rajikaimal/Bassa/commit/03ca956016240b59e1d9de372dacaa9bc5910317)

### CODE REVIEW

**Comment by malithsen** [comment]
Hi @rajikaimal Can you also make the necessary changes in .travis.yml :)

**Comment by rajikaimal** [comment]
@malithsen Sure thing.

**Comment by rajikaimal** [comment]
@malithsen It's done.

**Comment by malithsen** [comment]
@rajikaimal Travis still fails because we don't have the instructions on `.travis.yml` to install and setup chrome. You might have to do something like this http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/

**Comment by rajikaimal** [comment]
@malithsen Travis is passing now ! :tada: Codacy is fine too.

**Comment by rehrumesh** [comment]
@rajikaimal Thanks for the effort. Really appreciate it.

**Comment by malithsen** [comment]
@rajikaimal great work :)

**Comment by rajikaimal** [comment]
@rehrumesh @malithsen Anytime 👍

**Pull request merged**
