### PR TITLE
Username on navbar

### LINKED ISSUE #490: User name should be displayed on the top (UX)
As of now, the user name does not get displayed anywhere on the screen. The only way to know the username would be to click the hamburger icon that show log out button. Displaying the user name over the top would improve the UX.

Current scenario :
user name

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
fixes #490

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
Added Username on the navbar. Also, the hamburger menu says 'Logout from XYZ' which becomes redundant if the username is displayed on the navbar. Hence, a power sign is displayed instead of the username.

screen shot 2018-10-02 at 8 08 22 pm


screen shot 2018-10-02 at 8 08 35 pm

**Comment by VibhorCodecianGupta** [comment]
@vivonk done!

**Comment by aakashbansal** [comment]
@VibhorCodecianGupta One suggestion. Whenever you are working on a new feature or issue, create a separate branch and then open pull request. This will keep your master branch clean. Also the pull request would not be cluttered with unrelated commits. Like here the readme-update commit is also merged with the feature-update commit. :)

**Comment by VibhorCodecianGupta** [comment]
I know what you're saying, I was just too lazy to create another branch :P 
But ofcourse I create separate branches for separate issues, no question about that. Also, the readme change was pretty insignificant, I purposefully clubbed it with the UI change. Cheers!

**Comment by VibhorCodecianGupta** [comment]
@agentmilindu any updates here?

**Pull request merged**
