### PR TITLE
Now build shows only errors and other logs are redirected

### PR DESCRIPTION
**Pull request by kmehant**
## Description
Travis build is being failed to huge logs from docker builds.
Now we redirect all normal logs and only show when there is an error during the build process.

### CODE REVIEW

**Comment by kmehant** [comment]
@JaDogg 
@agentmilindu I have taken care of your comments in https://github.com/scorelab/Bassa/pull/920
I have closed that due to some local setup mess as I have used that for testing and digging out the problem. Now everything is fixed.

Please review!

**Comment by JaDogg** [comment]
Let's get this merged 🚀

**Comment by kmehant** [comment]
@agentmilindu Please review!

**Comment by kmehant** [comment]
@JaDogg  Shall we merge

**Pull request merged**
