### PR TITLE
Adding missing logo in the readme.md file

### PR DESCRIPTION
**Pull request by csl7**
## Description
In the readme.md file the logo associated to the product was missing. Therefore I changed it to display the logo.

## Related Issue
N/A

## Motivation and Context
Since this page gives the first impression to the user, better if repository have the missing logo.

## How Has This Been Tested?
This was tested using locally as well as in the GitHub web readme.md web page of the repository.

## Types of changes
This how it was displayed before adding the image with new path
image

This how now the product logo is going to be displayed in the repository
image

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kmehant** [comment]
Looks like you have got few commits from the master branch added to your pull request can you remove them 😁

**Comment by 7slcode7** [comment]
@JaDogg  @kmehant Thank you for reviewing. Added suggested changes.

**Comment by JaDogg** [comment]
It would be easier to create a new pull request by branching from develop, updating README, then sending the pull request.

**Comment by JaDogg** [comment]
I can still see all the changes. No need to add what's in Master branch :)

**Comment by 7slcode7** [comment]
@JaDogg Can you please check again now ?

**Comment by JaDogg** [comment]
Looks good to me. 😁😁😁

**Comment by 7slcode7** [comment]
@kmehant Please review.

**Comment by kmehant** [comment]
@JaDogg Please add a review here as your old review has been ignored due to a merge commit 😄

**Comment by 7slcode7** [comment]
@JaDogg Please review :)

**Comment by deshankoswatte** [comment]
Hi @csl7,@kmehant and @JaDogg,

I think this has already been fixed by https://github.com/scorelab/Bassa/pull/909.

**Comment by JaDogg** [comment]
I'm seeing a merge conflict. fix it please.

**Comment by kmehant** [comment]
Closing this 
Fixed at #909

**Pull request closed without merging**
