### PR TITLE
Implementing support for magnet links.

### PR DESCRIPTION
**Pull request by saisankargochhayat**
Looking for any invaluable suggestions.
@rehrumesh @malithsen

### CODE REVIEW

**Comment by saisankargochhayat** [comment]
## **Currently magnet links are working and torrent name is successfully extracted**.
-  URL or Magnet link , check in front end. -  completed
-  Handling of download name in Downloadmanager.py - completed
I have tested it with a few magnet links from extra.to and few other magnet link websites. And the url validation is intact.

**Comment by malithsen** [comment]
Hello @saisankargochhayat awesome effort

I was testing this with few links and found a weird issue. If there are other downloads which have not been started yet the link will be added properly. However if the magnet link is the first link to be added, it throws out a
`POST http://localhost:5000/api/download 400 (BAD REQUEST)`

Can you replicate this at your end?

**Comment by saisankargochhayat** [comment]
Adding a certain magnet link -
screenshot from 2017-03-19 22-28-26
Added to downloads -
screenshot from 2017-03-19 22-28-50
Download started -
screenshot from 2017-03-19 22-29-53
@malithsen i am unable to replicate the error , can you tell me what exactly went wrong ?

**Comment by malithsen** [comment]
I restarted all three servers and now I am unable to recreate the issue as well. 

Will merge soon after testing few more times.
Good stuff @saisankargochhaya :+1:

**Comment by saisankargochhayat** [comment]
@malithsen thanks. :smile:

**Pull request merged**
