### PR TITLE
breaking Rest.py into Routes/ and renamed to Server.py

### LINKED ISSUE #324: Breakdown REST.py into manageable subparts
I think we should break the `REST.py` into several parts as following,

Rename REST.py into Server.py
Create a directory as Routes/ and put an `index.py`
Create a User.py in `Routes` and add all the User related routes there.
Create a Download.py in `Routes` and add all the Download related routes there.
etc. 

And finally, import all these Route files in `Routes` directory into `index.py` and then import this Routes into new `Server.py`

### PR DESCRIPTION
**Pull request by vivonk**
### old structure
```
components/
           core/
                Rest.py
```
### new structure
```
components/
           core/
               Server.py
               Routes/
                      User.py
                      Download.py
```
## Code changes
- Added `flask.blueprint` for making blueprint of other modules in `Server.py`
- Improved code quality in `Server.py`,`User.py ` and `Download.py`
- In previous PR #400 , UI was getting break because the socket server was not understanding paths, so now making `Blueprint` of other modules make it working 
## Motivation and Context
By breaking module in this manner make it easy to understand

## Screenshots (In case of UI changes):
 In previous PR, UI was breaking down but now it's working fine

## Types of changes

- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

Signed-off-by: Nirmal Sarswat <nirmalsarswat400@gmail.com>

### CODE REVIEW

**Comment by vivonk** [comment]
@agentmilindu @charithccmc Work is done but one issue raised on 
```
c = urllib.request.urlopen('http://localhost:6800/jsonrpc', jsonreq)
```
> Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.

Some [reference for the issue](https://docs.openstack.org/bandit/latest/api/bandit.blacklists.html#b310-urllib-urlopen)

**Comment by vivonk** [comment]
@agentmilindu @charithccmc @malithsen  please review this one 😄

**Comment by vivonk** [comment]
@agentmilindu @malithsen please review this one

**Comment by agentmilindu** [comment]
@vivonk Can you please explain why we need `Blueprints` here, I'm not familiar with it,

**Comment by agentmilindu** [comment]
@rehrumesh @malithsen @rajikaimal @saisankargochhayat @padamchopra please review.

**Comment by vivonk** [comment]
@agentmilindu In Flask, when your code is in different modules and our files in other directories should be considered with the same web app then we use blueprint for making a single application from different modules of code/file. A good insight into what I am talking is [here](http://flask.pocoo.org/docs/0.12/blueprints/#blueprints)

**Comment by malithsen** [comment]
Hi @vivonk Great job :+1: 
Can you please sync your branch with master and resolve the conflicts

**Comment by rehrumesh** [comment]
components/core/Routes/Download.py
components/core/Routes/User.py
components/core/Server.py

Above 3 files have merge conflicts.

**Comment by vivonk** [comment]
Merge conflicts are because of last commit of @padamchopra in the same files. In those commits, Download APIs are not working. So should I squash the commits or push commits back after sync with latest master

**Comment by vivonk** [comment]
This work has done in https://github.com/scorelab/Bassa/issues/462 but using import after loading sources not seems a good way. Anyway, the work is done so can we close this thread for further @agentmilindu @rehrumesh

**Comment by vivonk** [comment]
This work has been done in #475. Closing this thread

**Pull request closed without merging**
