### PR TITLE
Error handling code in login

### PR DESCRIPTION
**Pull request by hkhatri241**
## Description
Added a try except block in get_user() in UserManager.py and appropriate conditions in REST.py.

## How Has This Been Tested?
Functional Testing 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rajikaimal** [comment]
@hkhatri241 Unit tests are failing, it's kinda weird since you haven't touched anything related to front-end code.

**Comment by saisankargochhayat** [comment]
@rajikaimal @hkhatri241 those tests are failing due to the angular version , please pull and merge the master branch to your pr , that should fix the travis issue.

**Comment by rajikaimal** [comment]
Angular version in this PR is 1.6.0 probably. I have a local instance with the same version. Unit tests are passing.

**Comment by saisankargochhayat** [comment]
Yeah angular in this PR is 1.6.3 , 1.6.0 does work in local environment , but in the travis container it cant seem to find the same so its causing the build to fail .

**Comment by agentmilindu** [comment]
@malithsen @rehrumesh Can we merge this PR?

**Comment by vivonk** [comment]
@agentmilindu are we merging commits directly to the master branch?

**Comment by kmehant** [comment]
@hkhatri241  This **PR** seems to be way too old.
Right now on `develop` branch Bassa API server code base has been made more _modular_ and endpoints have been separately defined in Main.py. As per the files changed in this **PR** 
Only changes made to `UserManager.py` seems to be useful. So I appreciate if you could make a new **PR**  to the `develop` branch making those changes. Thank you!
@vivonk @agentmilindu I am closing this for now.

**Pull request closed without merging**
