### PR TITLE
Made setup compatible with apt-get and pacman

### PR DESCRIPTION
**Pull request by prabushitha**

### CODE REVIEW

**Comment by agentmilindu** [comment]
@malithsen @rehrumesh Can we merge this PR?

**Comment by agentmilindu** [comment]
@prabushitha Please resolve conflicts, we need to merge this. Good job.

**Comment by vivonk** [comment]
I feel `pacman` is more specific to Arch Linux so why we are about to use it?

**Comment by prabushitha** [comment]
Yes, it's not practical to make it compatible to each and every package manager. Therefore, I will be closing this issue. If anyone needs arch instructions, this would be avaialble in the closed issues.

**Comment by agentmilindu** [comment]
I think we can merge this. There is no harm supporting just a few major package managers.

**Pull request merged**
