### PR TITLE
Adding Basic Installation Configuration

### PR DESCRIPTION
**Pull request by scorpionhiccup**
- Adding Requirements.txt file
- Update README with
  * Install Instructions
  * Running Instructions
- Exclude Server Log Files from the git repo.
- Installing the required packages with the help of setup.py file and requirements.txt

### CODE REVIEW

**Comment by scorpionhiccup** [comment]
Any Updates on this issue?

**Comment by paarandika** [comment]
How about adding dependencies to existing ```setup.py```?

**Comment by scorpionhiccup** [comment]
Hey I have added the dependencies in the setup.py file.  Can you have a look now?

**Comment by paarandika** [comment]
I will merge as soon as I test the script

**Comment by paarandika** [comment]
```python
No module named flask.ext.cors
```
I think you should add matching flask version or add flask-cors to requirements.txt

**Comment by paarandika** [comment]
Seems to work correctly. I reverted the PR accidently. Can you send another PR?
And also add
```
sudo apt-get install libmysqlclient-dev
sudo apt-get install python-dev
```
to readme as well. For installation we prefer 
```
$sudo python setup.py develop
``` 
since its currently only for dev purposes. And for running ```$bassa```

**Pull request merged**
