### PR TITLE
improve login section in short screen

### PR DESCRIPTION
**Pull request by avsingh999**
#716 
## Description

scor6

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by avsingh999** [comment]
@vivonk @kmehant Please review me 
thanks : )

**Comment by vivonk** [comment]
Can you please resolve the conflicts @avsingh999 ?

**Comment by avsingh999** [comment]
@vivonk But It's showing I don't have write access.

**Comment by vivonk** [comment]
You should have write access as it's your PR. Anyway, change to your branch and then again commit the changes

**Comment by kmehant** [comment]
> @vivonk @kmehant Please review me
> thanks : )

I see that you are working on `avsingh999:master` to merge your feature in to `develop` branch. The best and clean practice would be to checkout a branch from `develop` branch having a proper name to your `feature` branch and then merging your feature in to `develop`. This would surely reduce the tendency of encountering conflicts.

**Comment by avsingh999** [comment]
@vivonk @kmehant I am setting with develop branch but I am getting error while run this command
```mysql -u root -p  Bassa < Bassa.sql```
**error**
`ERROR 1062 (23000) at line 91: Duplicate entry 'rand' for key 'PRIMARY'
`

**Comment by avsingh999** [comment]
@vivonk @kmehant I have open new pr Please review

**Pull request closed without merging**
