### PR TITLE
[Docs] Add commands to run unit tests locally

### PR DESCRIPTION
**Pull request by rajikaimal**
Added commands to instruct developers to run unit tests.
## Description

This document improvement will assist developers who are interested in contributing to unit tests.
## Motivation and Context

To improvement collaboration.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by malithsen** [comment]
Thanks for the PR @rajikaimal
Do we need this commit https://github.com/scorelab/Bassa/pull/92/commits/92f59fe5f07c7604402aa747ae23370cfaafca8f ?

**Comment by rajikaimal** [comment]
Actually no, I was wondering why the build failed, I'll close this and submit a separate PR for this. Thanks for pointing it out.

**Comment by rajikaimal** [comment]
After going through the commit realized that this doesn't have an impact on the build. `.travis.yml` is not affected by this since this was changed again in the later commit. Not so sure why this shows up here though. Build fails due to recent change in Angular version.

**Comment by malithsen** [comment]
@rajikaimal Merged your PR. But we need to look into why Travis build fails

**Comment by rajikaimal** [comment]
@malithsen I'll look into it, as I mentioned it's due to a recent change in Angular version.

**Pull request merged**
