### PR TITLE
Updated Dockerfile for API server

### PR DESCRIPTION
**Pull request by demon-36**
## Description

Updated Dockerfile to successfully build Docker Image for core server, As currently Dockerfile fails to build Docker Image.

- Used `ubuntu as base` image
- Added commands to install `pip` and `python-setuptools` as they are not pre-installed with base image
- Added required steps to install `pylint`
- Updated `setup.sh` for core to allow installation of `libmysqlclient`

## Related Issue

#786 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by demon-36** [comment]
@vivonk  @agentmilindu I have used `ubuntu as base` image as it will have required packages for Bassa and also small in size(around 70MB) and faster than standard image.
Currently this image is around 850 MBs and will be reduced after separating `aria2c`
I will separate `aria2c` and `core server` as different containers in coming days

**Comment by demon-36** [comment]
@vivonk  @agentmilindu  I have used `ubuntu as base` image as it will have required packages for Bassa and also small in size(around 70MB) and faster than standard image.
Built docker image for API server is around 850 MBs and will be reduced after testing `aria2c` and `core server` as different containers in coming days

**Comment by vivonk** [comment]
@demon-36 @kmehant can you please review each others PR on same changes. I will approve one of these. #782

**Comment by kmehant** [comment]
> @demon-36 @kmehant can you please review each others PR on same changes. I will approve one of these. #782

@vivonk @demon-36  #776 got merged so we can safely close this PR 😃

**Pull request closed without merging**
