### PR TITLE
Fix Server errors for download and compression feature and other required fixes

### PR DESCRIPTION
**Pull request by kmehant**
## Description

There some serious server errors while making downloads and usually the server goes down due to improper concurrency. I have made required fixes as follows
1. Updated base image to use alpine latest for Aria2c due to support issues
2. Resolved MySQL exceptions and type errors and added logging
3. Removed pool size restriction for now
4. Increased `max_bandwidth` and `size_limit` for downloads as users are restricted after downloading a few KB of data.
5. Corrected URL endpoints for start and kill downloads
6. According to the previous model for every start request, a new process is being spawned creating problems with huge concurrency giving out various problems. I reformed the model to have always a single process for download daemon with 5 worker threads to download to the max of five files at a time concurrently.
7. Fixed the Compression feature and now we can have downloads and compression feature working \0/

## Motivation and Context
This is required for the proper functioning of the server.

## How Has This Been Tested?
This has been tested locally and it's working fine now.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kmehant** [comment]
@JaDogg I fixed most of them the one which is there is according to the previous code practice :)

**Comment by kmehant** [comment]
@JaDogg and also Travis is failing because the log limit is being crossed. So will work on some workaround for this in my next pull request :)

**Comment by JaDogg** [comment]
@kmehant Need 1 more review to merge :)

**Comment by kmehant** [comment]
> @kmehant Need 1 more review to merge :) 

@jadogg I cannot approve my own PR 😫
We might need to reduce threshold to 1 or might need some other to approve as well.

**Comment by agentmilindu** [comment]
Problem solved!

**Comment by JaDogg** [comment]
Merged :)

**Pull request merged**
